### ISSUE TITLE
How to deploy template on github pages?

### ISSUE THREAD

**Issue by Viluppo** [dunky11/react-saas-template#168]
Hola buenas noches queria saber si se puede implementar en github pages ya que no lo logro hacer funcionar.

**Comment by dunky11** [comment]
Im sorry, I don't speak spanish. You said the app doesn't work outside of github pages? The deployment is quite simple. You go into the directory of your repository and run

`npm run build`

It will create a folder named build inside your webroot. After that you just copy the content of that folder into the webroot of your server.

About the deployment using github-pages. It could lead to some problems with the routing of the app. You also probably have to change the "homepage" key inside your package.json. I will try to get it running using github-pages today and let you know.

**Comment by dunky11** [comment]
Okay, as it works until you refresh the page. Then you have to navigate to the homepage again, otherwise you get a 404. To fix it you would have to look over all the links in the repository and change them accordingly.

This is the gh-pages website:
https://dunky11.github.io/react-saas-template-gh-pages

This is the repository:
https://github.com/dunky11/react-saas-template-gh-pages

Heres how you can do it:

1. Activate gh-pages on your preferred branch inside your repository settings.
2. Change the homepage key of package.json:

package.json

{
     ...,
    homepage: "username.github.io/your-repository-name"
    ...,
}

3. Run npm run build
4. Copy the content of the build folder to your repositories root, like I did here: https://github.com/dunky11/react-saas-template-gh-pages
5. Push to the branch you activated gh-pages on in step 1

**Comment by Viluppo** [comment]
Muchas gracias! realmente! muy conforme con la respuesta.
