### ISSUE TITLE
Invalid usage of pushMessageToSnackbar & setPushMessageToSnackbar

### ISSUE THREAD

**Issue by donovanly** [dunky11/react-saas-template#177]
In the below code snippets, the use of pushMessageToSnackbar & setPushMessageToSnackbar is reversed.

https://github.com/dunky11/react-saas-template/blob/76975909a0997c252b2b6a95bfdcfac005ed11dd/src/logged_in/components/Main.js#L83-L88

https://github.com/dunky11/react-saas-template/blob/76975909a0997c252b2b6a95bfdcfac005ed11dd/src/logged_in/components/Main.js#L217-L230

https://github.com/dunky11/react-saas-template/blob/76975909a0997c252b2b6a95bfdcfac005ed11dd/src/logged_in/components/Main.js#L299-L301

https://github.com/dunky11/react-saas-template/blob/76975909a0997c252b2b6a95bfdcfac005ed11dd/src/logged_in/components/Main.js#L341

**Comment by dunky11** [comment]
Thanks man, sorry i don't have much time this week. I will make a fix on the weekend.

**Comment by dunky11** [comment]
I think it's correct. pushMessageToSnackbar is a state of Main.js. setPushMessageToSnackbar is the setter of that state.

In the snippet below I define a callback function which will get called by <ConsecutiveSnackbarMessages/> on mount. This will pass its pushMessage function to the state of Main.js. I had to use some weird anonymous function syntax which will return another function because you cannot pass functions to the state of functional components directly.
https://github.com/dunky11/react-saas-template/blob/76975909a0997c252b2b6a95bfdcfac005ed11dd/src/logged_in/components/Main.js#L299-L301

**Comment by dunky11** [comment]
Gonna close this due to inactivity.
